In [1]:
import pandas as pd
import os
import jieba
from torch.nn import functional as F
import torch
import numpy as np
import time

In [98]:
data_train = pd.read_csv("data\ChnSentiCorp_htl_all\\train_1600+1600.csv",header=0,names=['label','sentence'],keep_default_na=False)# label, review
stop_word = pd.read_csv("data/stop_words.csv",header=None,sep='!').values
# print(data_train[:10])
print(stop_word.shape)
print(data_train.shape)

(1179, 1)
(3200, 2)


In [ ]:
all_sentence = data_train.iloc
print(type(all_sentence))
print(all_sentence.shape)

In [99]:
word_set = {}
id = 0
for item in data_train.values:
    words = jieba.lcut(item[1])
    id+=1
    if id == 2653:
        print(item)
    for i in words:
        # if i in stop_word:
        #     continue
        try:
            word_set[i]+=1
        except:
            word_set[i]=1

# print(len(word_set))
word_set_sort = sorted(word_set.items(),key=lambda x:x[1],reverse=False)
# print(word_set_sort[:50])


[0 '']


In [74]:
cnt = 0
other_cnt = 0
for i in word_set.items():
    if i[1] >= 100: 
        cnt+=1
    else:
        other_cnt+=i[1]

print(cnt)
print(other_cnt)

219
77711


In [2]:

label = 0
label = torch.zeros(2, dtype=torch.float).scatter_(dim=0, index=torch.tensor(label), value=1)
print(label)

tensor([1., 0.])


In [4]:
v1 = torch.rand(5,2)
v2 = torch.rand(5,2)
v = torch.cat((v1,v2),1)
print(v.shape)

torch.Size([5, 4])


In [111]:

keys = ['a','af']

wd_dict = dict(zip(keys, np.zeros(len(keys))) )
print((torch.tensor(list(wd_dict.values()))))

tensor([0., 0.], dtype=torch.float64)


In [ ]:

tt = 0.0
y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)

y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
loss/=4.0
print(loss)
print('\n')

y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)
y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
print(tt)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
print(loss/4.0)

In [ ]:

input = torch.rand((4,2))*100
print(input)
x=input
x = F.softmax(x,dim=-1)
torch.log_(x)
print(x)

x = input
x = F.log_softmax(x, dim=-1)
print(x)


In [ ]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad)
w.grad = None
b.grad = None
# x[0] = 1
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad)


In [3]:

now = int(round(time.time()*1000))
tm = time.localtime(now/1000)
print(f"{tm}")

time.struct_time(tm_year=2021, tm_mon=12, tm_mday=28, tm_hour=10, tm_min=7, tm_sec=30, tm_wday=1, tm_yday=362, tm_isdst=0)


In [1]:
lt = [1]*10
print(lt)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [5]:
m = torch.nn.Dropout(p=0.2)
input = torch.randn(20, 16)
output = m(input)
print(output)

tensor([[ 5.2462e-01,  3.3580e-01,  1.4399e+00,  2.2043e-01,  5.0470e-01,
         -0.0000e+00,  1.2358e-01, -3.9067e-01,  1.6860e+00, -0.0000e+00,
         -1.0877e-01,  1.9628e-01,  9.1246e-01,  7.4128e-01,  0.0000e+00,
         -8.5440e-02],
        [-8.4848e-01,  1.5464e-01, -3.4464e-01,  0.0000e+00, -7.3336e-01,
         -1.2872e+00, -0.0000e+00,  1.4119e+00,  3.0855e-01, -5.9190e-01,
          3.6452e+00,  0.0000e+00, -9.9343e-01, -0.0000e+00,  1.0132e+00,
          1.3593e+00],
        [-5.6101e-01, -4.3539e-01,  1.3291e+00, -1.4730e+00, -5.9722e-01,
         -4.3017e-01,  2.0307e+00,  1.1433e+00, -8.5839e-01,  6.4796e-01,
          1.0786e+00,  6.1886e-01, -2.1661e-01, -3.2959e-01, -1.9487e-01,
         -0.0000e+00],
        [ 9.9750e-01,  1.3809e+00,  0.0000e+00, -0.0000e+00,  1.6244e+00,
         -0.0000e+00, -6.9642e-01, -9.8187e-01, -0.0000e+00,  7.7633e-01,
          8.9039e-01, -9.7560e-01,  7.2703e-01, -1.6321e+00,  1.1412e+00,
         -0.0000e+00],
        [-0.0000e+00