In [1]:
import pandas as pd
import os
import jieba
from torch.nn import functional as F
import torch
import numpy as np
import time

In [ ]:
ts1 = torch.tensor([[[1,1,1],[1,1,1]],[[2,2,2],[2,2,2]],[[1,1,1],[1,1,1]]],dtype=torch.float64)
# 3*1*2*3
ts1 = ts1.reshape((3,1,2,3))
ts2 = torch.ones((2,3,2),dtype=torch.float64)

res1 = ts1@ts2 #3*2*2*2
res2 = ts1@ts2 #3*2*2*2
print(res1)
res = res1@res2
print(res.shape)

In [2]:
mask_prob=0.15
mask_pos=[1,1,1,1,1]
mask_num:int = len(mask_pos)*mask_prob
print(mask_pos[mask_num])

TypeError: list indices must be integers or slices, not float

In [98]:
data_train = pd.read_csv("data\ChnSentiCorp_htl_all\\train_1600+1600.csv",header=0,names=['label','sentence'],keep_default_na=False)# label, review
stop_word = pd.read_csv("data/stop_words.csv",header=None,sep='!').values
# print(data_train[:10])
print(stop_word.shape)
print(data_train.shape)

(1179, 1)
(3200, 2)


In [ ]:
all_sentence = data_train.iloc
print(type(all_sentence))
print(all_sentence.shape)

In [99]:
word_set = {}
id = 0
for item in data_train.values:
    words = jieba.lcut(item[1])
    id+=1
    if id == 2653:
        print(item)
    for i in words:
        # if i in stop_word:
        #     continue
        try:
            word_set[i]+=1
        except:
            word_set[i]=1

# print(len(word_set))
word_set_sort = sorted(word_set.items(),key=lambda x:x[1],reverse=False)
# print(word_set_sort[:50])


[0 '']


In [74]:
cnt = 0
other_cnt = 0
for i in word_set.items():
    if i[1] >= 100: 
        cnt+=1
    else:
        other_cnt+=i[1]

print(cnt)
print(other_cnt)

219
77711


In [2]:

label = 0
label = torch.zeros(2, dtype=torch.float).scatter_(dim=0, index=torch.tensor(label), value=1)
print(label)

tensor([1., 0.])


In [2]:
l = [[1]*10]
l

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [111]:

keys = ['a','af']

wd_dict = dict(zip(keys, np.zeros(len(keys))) )
print((torch.tensor(list(wd_dict.values()))))

tensor([0., 0.], dtype=torch.float64)


In [ ]:

tt = 0.0
y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)

y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
loss/=4.0
print(loss)
print('\n')

y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)
y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
print(tt)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
print(loss/4.0)

In [ ]:

input = torch.rand((4,2))*100
print(input)
x=input
x = F.softmax(x,dim=-1)
torch.log_(x)
print(x)

x = input
x = F.log_softmax(x, dim=-1)
print(x)


In [ ]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad)
w.grad = None
b.grad = None
# x[0] = 1
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad)


In [3]:
now = int(round(time.time()*1000))
tm = time.localtime(now/1000)
print(f"{tm}")

time.struct_time(tm_year=2021, tm_mon=12, tm_mday=28, tm_hour=10, tm_min=7, tm_sec=30, tm_wday=1, tm_yday=362, tm_isdst=0)


In [2]:
import torch
os.environ['CUDA_VISIBLE_DEVICES']='1'  # here chose the GPU
torch.cuda.empty_cache()
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device')
device = torch.device(device)
ts1 = torch.Tensor([[1,2,3],[4,5,6]]).to(float).to(device)
print(ts1)

tensor([[0.5000, 1.0000, 1.5000],
        [1.3333, 1.6667, 2.0000]], dtype=torch.float64)
