In [2]:
import pandas as pd
import os
import jieba

In [98]:
data_train = pd.read_csv("data\ChnSentiCorp_htl_all\\train_1600+1600.csv",header=0,names=['label','sentence'],keep_default_na=False)# label, review
stop_word = pd.read_csv("data/stop_words.csv",header=None,sep='!').values
# print(data_train[:10])
print(stop_word.shape)
print(data_train.shape)

(1179, 1)
(3200, 2)


In [ ]:
all_sentence = data_train.iloc
print(type(all_sentence))
print(all_sentence.shape)

In [99]:
word_set = {}
id = 0
for item in data_train.values:
    words = jieba.lcut(item[1])
    id+=1
    if id == 2653:
        print(item)
    for i in words:
        # if i in stop_word:
        #     continue
        try:
            word_set[i]+=1
        except:
            word_set[i]=1

# print(len(word_set))
word_set_sort = sorted(word_set.items(),key=lambda x:x[1],reverse=False)
# print(word_set_sort[:50])


[0 '']


In [74]:
cnt = 0
other_cnt = 0
for i in word_set.items():
    if i[1] >= 100: 
        cnt+=1
    else:
        other_cnt+=i[1]

print(cnt)
print(other_cnt)

219
77711


In [2]:
import torch
label = 0
label = torch.zeros(2, dtype=torch.float).scatter_(dim=0, index=torch.tensor(label), value=1)
print(label)

tensor([1., 0.])


In [111]:
import numpy as np
keys = ['a','af']

wd_dict = dict(zip(keys, np.zeros(len(keys))) )
print((torch.tensor(list(wd_dict.values()))))

tensor([0., 0.], dtype=torch.float64)


In [ ]:
from torch.nn import functional as F
tt = 0.0
y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)

y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
loss/=4.0
print(loss)
print('\n')

y_pred = torch.rand((4,2),dtype=float,requires_grad=True)
y_pred = F.log_softmax(y_pred, dim=-1)
y_std = torch.randint(0,2,(4,),dtype=torch.long)
loss = F.nll_loss(y_pred, y_std)
tt+=loss
print(loss)
print(tt)
loss = 0.0
for i in range(4):
    loss+=(-y_pred[i][y_std[i]])

print(loss)
print(loss/4.0)

In [6]:
import torch
from torch.nn import functional as F
input = torch.rand((4,2))*100
print(input)
x=input
x = F.softmax(x,dim=-1)
torch.log_(x)
print(x)

x = input
x = F.log_softmax(x, dim=-1)
print(x)


tensor([[34.1650, 63.4272],
        [58.3093, 80.9953],
        [43.0227, 76.4752],
        [20.2296,  1.9914]])
tensor([[-29.2622,   0.0000],
        [-22.6860,   0.0000],
        [-33.4524,   0.0000],
        [  0.0000, -18.2382]])
tensor([[-29.2622,   0.0000],
        [-22.6860,   0.0000],
        [-33.4524,   0.0000],
        [  0.0000, -18.2382]])
